language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

install:
    - rustup target add armv7-unknown-linux-gnueabihf

script:
    - cargo build --verbose --all
    - cargo test --verbose --all

cache: cargo
before_cache:
    - chmod -R a+r $HOME/.cargo

branches:
    only:
        - master
