[package]
name = "flight-software"
version = "0.1.0"
authors = ["Project Caelus"]
edition = "2018"

[dependencies]
byteorder = "*"
i2cdev = "*"
i2csensors = "*"
rand = "0.6"
priority-queue = "0.6.0"
chrono = "0.4"
ws = "*"